static_pages:
  about:
    link3: "http://railstutorial.org/book"
    link2: "http://www.railstutorial.org/"
    link4: "http://screencasts.railstutorial.org/"
    link5: "http://rubyonrails.org/"
  help:
    link6: "http://www.railstutorial.org/help"
    link7: "http://www.railstutorial.org/book"
  home:
    link8: "http://www.railstutorial.org/"
  contact:
    link9: "http://www.railstutorial.org/contact"
layouts:
  footer:
    link2: "http://www.railstutorial.org/"
    link10: "http://www.michaelhartl.com"
    link11: "http://news.railstutorial.org/"
users:
  edit:
    link12: "http://gravatar.com/emails"
User:
  number: 50
  number1: 255
  number2: 6
  number3: 2
_user:
  size: 5
users_helper:
  size1: 80
users_controller:
  size2: 10
static_pages_controller:
  size3 : 15
Micropost:
  number4: 140
  number10: 5
_micropost:
  number5: 50
user_info:
  number6: 50
